[tool.poetry]
name = "lambda-utility"
version = "0.4.0"
description = ""
authors = ["Kyungmin Lee <rekyungmin@gmail.com>"]
maintainers = ["Kyungmin Lee <rekyungmin@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/rekyungmin/lambda-utils"
repository = "https://github.com/rekyungmin/lambda-utils"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.1"
slack-sdk = "^3.4.2"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
boto3 = "^1.17.30"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
